version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-crud
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
