version: "3.9"

services:
  web:
    image: docker.io/mayhun28/fastapi-crud:${IMAGE_TAG}
    container_name: fastapi-crud
    ports:
      - "8000:8000"                                         
    restart: unless-stopped
    env_file:
      - .env                                              
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
