name: Build & Push to Docker Hub + Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: docker-push
  cancel-in-progress: true

env:
  IMAGE_NAME: mayhun28/fastapi-crud # (username/repository)

jobs:
  # 빌드 & 푸시
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:latest
            docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify pushed image
        run: |
          docker buildx imagetools inspect docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # 1) EC2에 앱 디렉토리 보장
      - name: Ensure app dir on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}   # Ubuntu면 'ubuntu'
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            mkdir -p "$HOME/app"

      # 2) 로컬 레포의 docker-compose.yml 업로드 (경로가 다르면 source 수정)
      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.EC2_USER }}/app"

      # 3) 배포: Docker Hub 로그인 → IMAGE_TAG 주입 → pull+up
      - name: Deploy on EC2 (pull & restart)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            cd "$HOME/app"

            # .env는 EC2에만(이미 수동 업로드했다는 전제)
            if [ ! -f .env ]; then
              echo "❌ $PWD/.env 가 없습니다. (.env는 깃에 올리지 말고 EC2에만 두세요)"
              exit 1
            fi

            # Docker Hub 로그인(프라이빗/레이트리밋 대비)
            docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            # 이번 커밋으로 태그 주입 → compose에서 ${IMAGE_TAG} 사용
            export IMAGE_TAG=${GITHUB_SHA}

            # 서버 빌드 없이 최신 이미지 적용
            docker compose up -d --pull always --no-build