name: Build & Push to Docker Hub

on:
  push:
    branches: [ "main" ]      # main에 푸시할 때 동작
  workflow_dispatch:           # 수동 실행도 가능

concurrency:
  group: docker-push
  cancel-in-progress: true

env:
  # ⬇️ 네 Docker Hub 레포로 변경 (예: mayworld/fastapi)
  IMAGE_NAME: mayhun28/fastapi-curd

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 빌드캐시/빌드엑스 준비(선택이지만 속도↑, 권장)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:latest
            docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # (옵션) 방금 푸시된 이미지가 레지스트리에 존재하는지 확인
      - name: Verify pushed image
        run: |
          docker buildx imagetools inspect docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
